# Qus: 1==>
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

In [2]:
arr = np.arange(2,51,3)
print(arr)
arr.size

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


17

# Qus: 2==>
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it

In [3]:

l1 = list(int(i) for i in input(" list 1 : enter 5 element separated by space: \t").split())[:5]
print(" list-1 :", l1)
print(type(l1))
print()
l2 = list(int(j) for j in input(" list 2 : enter 5 element separated by space: \t").split())[:5]
print(" list-2 :", l2)
print(type(l2))
print()
arr1 = np.array(l1)
print(" aray-1 :",arr1)
print(type(arr1))
print()
arr2 = np.array(l2)
print("array-2 :",arr2)
print(type(arr2))
print()
con=np.concatenate([arr1 , arr2])
print("concatenation :",con)
print(type(con))
print()
srt = np.sort(con)
print("sort :",srt)

 list 1 : enter 5 element separated by space: 	1 2 6 8 8
 list-1 : [1, 2, 6, 8, 8]
<class 'list'>

 list 2 : enter 5 element separated by space: 	9 5 21 58 63
 list-2 : [9, 5, 21, 58, 63]
<class 'list'>

 aray-1 : [1 2 6 8 8]
<class 'numpy.ndarray'>

array-2 : [ 9  5 21 58 63]
<class 'numpy.ndarray'>

concatenation : [ 1  2  6  8  8  9  5 21 58 63]
<class 'numpy.ndarray'>

sort : [ 1  2  5  6  8  8  9 21 58 63]


# Qus 3: ==>
Write a code snippet to find the dimensions of a ndarray and its size.


In [2]:
#1-D array
a_1d = np.arange(3)
print(a_1d)
print(a_1d.ndim)
print(a_1d.size)

#2-D array
a_2d = np.arange(9).reshape(3,3)
print(a_2d)
print(a_2d.ndim)
print(a_2d.size)

#N-D array
a_nd = np.arange(36).reshape(3,4,3)
print(a_nd)
print(a_nd.ndim)
print(a_nd.size)





[0 1 2]
1
3
[[0 1 2]
 [3 4 5]
 [6 7 8]]
2
9
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
3
36


In [7]:
# This is an example snippet!
# To create your own, add a new snippet block to the
# snippets.json file in your jupyter nbextensions directory:
# /nbextensions/snippets/snippets.json
import this

# Qus: 4==>
How to convert a 1D array into a 2D array

In [8]:
#1-D array
import numpy as np
one_d = np.arange(6)
print(one_d)
np.shape(one_d)

[0 1 2 3 4 5]


(6,)

In [12]:
#using  np.expand_dims
two_d = np.expand_dims(one_d, axis=1) 
print(two_d)
np.shape(two_d)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [14]:
#using np.newaxis
new = one_d[:,np.newaxis]
print(new)
np.shape(new)


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)